/* Read-only talent-tree modal. Geometry + allocations come from
   src/data/talents.json (generated by `pnpm page` from the planner export +
   tlicompendium master bundle) — nothing here is editable or hand-positioned.
   The stage shown follows the Linear checkboxes via the trigger map the
   caller passes in; pills let the reader look ahead without touching state. */
import talentData from "./data/talents.json";
import { esc, escAttr } from "./ui";

interface TalentNode { id: string; type: string; x: number; y: number; max: number; desc: string }
interface TalentNotable { id: string; name: string; desc: string; threshold: number }
interface TalentTree {
  name: string; maxPoints: number;
  nodes: TalentNode[]; edges: [string, string][]; notables: TalentNotable[];
}
interface MirroredNode { id: string; from: string; x: number; y: number; points: number }
interface SlotPrism { name: string; node: string; replacesCore: boolean; effect: string | null }
interface StageSlot {
  tree: string; points: Record<string, number>;
  notable12: string | null; notable24: string | null;
  mirrored: MirroredNode[] | null;
  prism: SlotPrism | null;
}
interface TalentData {
  trees: Record<string, TalentTree>;
  stages: { loadout: string; slots: StageSlot[] }[];
}
/* a stage composes each tree slot from a (possibly different) loadout, so a
   single buy (e.g. the Frostbite slate) can advance one tree without dragging
   along unrelated changes the planner bundled into the same loadout.
   prism:false strips a slot's prism when the composed moment predates its move. */
export interface StageSlotRef { loadout: string; prism?: boolean }
export interface TreeStage { label: string; trigger: string | null; slots: StageSlotRef[] }

const DATA = talentData as unknown as TalentData;
const R: Record<string, number> = { micro: 15, medium: 20, legendary: 24 };

let STAGES: TreeStage[] = [];
let getDone: () => Record<string, true> = () => ({});
let dlg: HTMLDialogElement | null = null;
let tip: HTMLDivElement | null = null;
let viewIdx = 0;

export function initTalents(stages: TreeStage[], done: () => Record<string, true>): void {
  for (const s of stages) {
    if (s.slots.length !== 4) throw new Error(`talents: stage "${s.label}" needs 4 slots`);
    for (const ref of s.slots)
      if (!DATA.stages.some(d => d.loadout === ref.loadout))
        throw new Error(`talents: no loadout "${ref.loadout}" in talents.json`);
  }
  STAGES = stages;
  getDone = done;
}

/* the furthest stage whose trigger step is checked — checkbox-driven, order-free */
export function currentStageIdx(): number {
  const done = getDone();
  let cur = 0;
  STAGES.forEach((s, i) => { if (s.trigger && done[s.trigger]) cur = Math.max(cur, i); });
  return cur;
}

export function openTalents(idx?: number): void {
  viewIdx = idx ?? currentStageIdx();
  if (!dlg) {
    dlg = document.createElement("dialog");
    dlg.className = "tt-dlg";
    document.body.appendChild(dlg);
    dlg.addEventListener("click", e => {
      const t = e.target as HTMLElement;
      if (t === dlg || t.classList.contains("tt-close")) dlg!.close();
      const pill = t.closest<HTMLElement>("[data-idx]");
      if (pill) { viewIdx = +pill.dataset.idx!; render(); }
    });
    tip = document.createElement("div");
    tip.className = "tt-tip";
    tip.hidden = true;
    dlg.addEventListener("mousemove", e => {
      const g = (e.target as Element).closest<SVGElement>("[data-tip]");
      if (!g) { tip!.hidden = true; return; }
      tip!.innerHTML = g.dataset.tip!;
      tip!.hidden = false;
      const w = tip!.offsetWidth, h = tip!.offsetHeight;
      tip!.style.left = `${Math.min(e.clientX + 14, innerWidth - w - 8)}px`;
      tip!.style.top = `${Math.min(e.clientY + 14, innerHeight - h - 8)}px`;
    });
  }
  render();
  dlg.showModal();
}

const slotsOf = (i: number): StageSlot[] =>
  STAGES[i].slots.map((ref, k) => {
    const sl = DATA.stages.find(d => d.loadout === ref.loadout)!.slots[k];
    return ref.prism === false ? { ...sl, prism: null } : sl;
  });

function render(): void {
  const cur = currentStageIdx();
  const prev = viewIdx > 0 ? slotsOf(viewIdx - 1) : null;
  dlg!.innerHTML =
    `<div class="tt-panel"><div class="tt-head">`
    + `<h3>Talent Tree</h3>`
    + `<div class="tt-stages">` + STAGES.map((s, i) =>
        `<button data-idx="${i}" class="tt-pill${i === viewIdx ? " active" : ""}"`
        + ` title="${escAttr([...new Set(s.slots.map(r => r.loadout))].join(" + "))}">`
        + `${esc(s.label)}${i === cur ? `<span class="tt-now">now</span>` : ""}</button>`).join("")
    + `</div><button class="tt-close" aria-label="Close">✕</button></div>`
    + `<p class="tt-legend">hover a node for its stats — `
    + `<span class="tt-k tt-k-alloc">●</span> allocated · `
    + `<span class="tt-k tt-k-gain">◍</span> added this stage · `
    + `<span class="tt-k tt-k-drop">◌</span> respec out · `
    + `<span class="tt-k tt-k-inv">◆</span> inverse image copy · `
    + `<span class="tt-k tt-k-prism">◇</span> prism socket</p>`
    + `<div class="tt-grid">`
    + slotsOf(viewIdx).map((sl, k) => treeFig(sl, prev?.[k] ?? null)).join("")
    + `</div></div>`;
  dlg!.appendChild(tip!);
}

function treeFig(sl: StageSlot, prev: StageSlot | null): string {
  const tree = DATA.trees[sl.tree];
  const sameTree = prev !== null && prev.tree === sl.tree;
  const prevPts = (id: string): number => !sameTree ? 0
    : prev!.points[id] ?? prev!.mirrored?.find(m => m.id === id)?.points ?? 0;
  const total = Object.values(sl.points).reduce((a, b) => a + b, 0)
    + (sl.mirrored?.reduce((a, m) => a + m.points, 0) ?? 0);

  const pos = new Map(tree.nodes.map(n => [n.id, n]));
  const mirroredCells = new Set(sl.mirrored?.map(m => `${m.x},${m.y}`) ?? []);
  const xs = tree.nodes.map(n => n.x), ys = tree.nodes.map(n => n.y);
  const vb = `${Math.min(...xs) - 44} ${Math.min(...ys) - 44} `
    + `${Math.max(...xs) - Math.min(...xs) + 88} ${Math.max(...ys) - Math.min(...ys) + 88}`;

  const edges = tree.edges.map(([a, b]) => {
    const A = pos.get(a)!, B = pos.get(b)!;
    const lit = (sl.points[a] ?? 0) > 0 && (sl.points[b] ?? 0) > 0;
    return `<line class="tt-edge${lit ? " lit" : ""}" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`;
  }).join("");

  const circle = (id: string, x: number, y: number, r: number, type: string, pts: number,
                  was: number, desc: string, max: number, inv: boolean): string => {
    const cls = `tt-node t-${type}${pts > 0 ? " alloc" : ""}${inv ? " inv" : ""}`;
    const hasPrism = sl.prism?.node === id;
    // ethereal base affixes / core overrides replace the socketed node's original text
    // (e.g. Haze's +12% 1H AD over a Bladerunner move-speed legendary)
    const shown = hasPrism && sl.prism!.effect ? sl.prism!.effect : desc;
    const diff = !sameTree && prev !== null ? "" // whole-tree respec — badge carries it
      : pts > was ? "gain" : pts < was ? "drop" : "";
    const tipHtml = `<span class="tip-desc">${esc(shown).replace(/\n/g, "<br>")}</span>`
      + `<span class="tip-meta">${pts}/${max} points · ${type}</span>`
      + (diff === "gain" ? `<span class="tip-gain">● added this stage (${was} → ${pts})</span>` : "")
      + (diff === "drop" ? `<span class="tip-drop">◌ respec out this stage (was ${was})</span>` : "")
      + (inv ? `<span class="tip-inv">◆ inverse image copy</span>` : "")
      + (hasPrism ? `<span class="tip-prism">◇ ${esc(sl.prism!.name)}`
          + `${sl.prism!.replacesCore ? " — replaces the core talent"
            : sl.prism!.effect ? " — overrides this talent" : " socketed here"}</span>` : "");
    const ring = diff
      ? `<circle class="tt-ring ${diff}" cx="${x}" cy="${y}" r="${r + 6}"/>` : "";
    const prismMark = hasPrism
      ? `<path class="tt-prism" d="M ${x} ${y - r - 10} L ${x + r + 10} ${y} L ${x} ${y + r + 10} L ${x - r - 10} ${y} Z"/>` : "";
    return `<g class="${cls}" data-tip="${escAttr(tipHtml)}">`
      + ring + prismMark
      + `<circle cx="${x}" cy="${y}" r="${r}"/>`
      + (type === "legendary" ? `<circle class="tt-halo" cx="${x}" cy="${y}" r="${r - 4}"/>` : "")
      + (pts > 0 ? `<text x="${x}" y="${y}">${pts}</text>` : "")
      + `</g>`;
  };

  const nodes = tree.nodes
    .filter(n => !mirroredCells.has(`${n.x},${n.y}`))
    .map(n => circle(n.id, n.x, n.y, R[n.type] ?? 15, n.type,
      sl.points[n.id] ?? 0, prevPts(n.id), n.desc, n.max, false))
    .join("");
  const mirrored = (sl.mirrored ?? []).map(m => {
    const src = pos.get(m.from)!;
    return circle(m.id, m.x, m.y, R[src.type] ?? 15, src.type, m.points, prevPts(m.id), src.desc, src.max, true);
  }).join("");

  const notables = [[12, sl.notable12], [24, sl.notable24]]
    .filter((p): p is [number, string] => p[1] !== null)
    .map(([th, id]) => {
      const n = tree.notables.find(x => x.id === id)!;
      return `<span class="tt-notable" title="${escAttr(n.desc)}">${th} · ${esc(n.name)}</span>`;
    }).join("");

  return `<figure class="tt-tree"><figcaption>`
    + `<span class="tt-name">${esc(tree.name)}</span>`
    + `<span class="tt-pts">${total}/${tree.maxPoints} pts</span>`
    + (sl.prism ? `<span class="tt-prismchip">◇ ${esc(sl.prism.name)}`
        + `${sl.prism.replacesCore ? " · replaces core talent"
          : sl.prism.effect ? ` · ${esc(sl.prism.effect.split("\n")[0])}` : ""}</span>` : "")
    + (prev !== null && !sameTree
        ? `<span class="tt-badge">new tree — respec out of ${esc(DATA.trees[prev.tree].name)}</span>` : "")
    + `</figcaption>`
    + `<svg viewBox="${vb}" role="img" aria-label="${escAttr(tree.name)} talent tree">${edges}${nodes}${mirrored}</svg>`
    + (notables ? `<div class="tt-notables">${notables}</div>` : "")
    + `</figure>`;
}
